spring.application.name=backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/omnidoc_db
spring.datasource.username=postgres
spring.datasource.password=Jiashin0604
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
