spring.datasource.url=jdbc:postgresql://localhost:5432/omnidoc_db
spring.datasource.username=postgres
spring.datasource.password=Jiashin0604

file.upload.dir=uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
