spring.application.name=backend

# PostgreSQL Database Configuration
spring.profiles.active=local
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=http://localhost:5173

# application-local.properties
#spring.datasource.url=jdbc:postgresql://localhost:5432/DATABASENAME
#spring.datasource.username=postgres
#spring.datasource.password=PASSWORD
#file.upload.dir=uploads
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB